import Foundation

struct ClipboardSettings: Codable, Equatable {
    var isCaptureEnabled: Bool
    var separator: String
    var maxItemCount: Int
    var maxItemSizeBytes: Int
    var suppressAdjacentDuplicates: Bool
    var persistClipboardContents: Bool
    var clearHistoryOnQuit: Bool
    var ignoredAppNames: [String]
    var ignoredAppBundleIdentifiers: [String]
    var ignoredPasteboardTypes: [String]
    var sensitiveContentPatterns: [String]

    init(
        isCaptureEnabled: Bool = true,
        separator: String = "\n\n",
        maxItemCount: Int = 100,
        maxItemSizeBytes: Int = 1_000_000,
        suppressAdjacentDuplicates: Bool = true,
        persistClipboardContents: Bool = false,
        clearHistoryOnQuit: Bool = true,
        ignoredAppNames: [String] = ClipboardSettings.defaultIgnoredAppNames,
        ignoredAppBundleIdentifiers: [String] = ClipboardSettings.defaultIgnoredAppBundleIdentifiers,
        ignoredPasteboardTypes: [String] = ClipboardSettings.defaultIgnoredPasteboardTypes,
        sensitiveContentPatterns: [String] = ClipboardSettings.defaultSensitiveContentPatterns
    ) {
        self.isCaptureEnabled = isCaptureEnabled
        self.separator = separator
        self.maxItemCount = Self.clampedItemCount(maxItemCount)
        self.maxItemSizeBytes = Self.clampedItemSize(maxItemSizeBytes)
        self.suppressAdjacentDuplicates = suppressAdjacentDuplicates
        self.persistClipboardContents = persistClipboardContents
        self.clearHistoryOnQuit = clearHistoryOnQuit
        self.ignoredAppNames = Self.sanitizedList(ignoredAppNames)
        self.ignoredAppBundleIdentifiers = Self.sanitizedList(ignoredAppBundleIdentifiers)
        self.ignoredPasteboardTypes = Self.sanitizedList(ignoredPasteboardTypes)
        self.sensitiveContentPatterns = Self.sanitizedList(sensitiveContentPatterns)
    }

    static let defaultIgnoredPasteboardTypes: [String] = [
        PasteboardTypeNames.transient,
        PasteboardTypeNames.concealed,
        PasteboardTypeNames.autogenerated,
        PasteboardTypeNames.onePassword,
        PasteboardTypeNames.typeIt4Me,
        PasteboardTypeNames.peterMaurerTransient,
        PasteboardTypeNames.pasteboardGenerator,
        PasteboardTypeNames.keeWeb
    ]

    static let defaultIgnoredAppNames: [String] = [
        "1Password",
        "Bitwarden",
        "Dashlane",
        "Enpass",
        "Keeper",
        "KeePass",
        "Keychain Access",
        "LastPass",
        "NordPass",
        "Proton Pass",
        "Secrets",
        "Strongbox"
    ]

    static let defaultIgnoredAppBundleIdentifiers: [String] = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.apple.keychainaccess",
        "com.bitwarden.desktop",
        "com.dashlane.dashlanephonefinal",
        "com.keepersecurity.KeeperPasswordManager",
        "com.lastpass.LastPass",
        "com.proton.pass.mac",
        "com.strongbox.mac"
    ]

    static let defaultSensitiveContentPatterns: [String] = [
        #"\b(password|passwd|passphrase)\s*[:=]"#,
        #"\b(api[_-]?key|secret|token)\s*[:=]"#,
        #"-----BEGIN (RSA |EC |OPENSSH |PGP )?PRIVATE KEY-----"#
    ]

    static func sanitizedLines(from text: String) -> [String] {
        sanitizedList(text.components(separatedBy: .newlines))
    }

    static func sanitizedList(_ values: [String]) -> [String] {
        var seen: Set<String> = []

        return values.compactMap { value in
            let sanitized = value.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !sanitized.isEmpty else {
                return nil
            }

            let key = sanitized.lowercased()
            guard seen.insert(key).inserted else {
                return nil
            }

            return sanitized
        }
    }

    func normalized() -> ClipboardSettings {
        ClipboardSettings(
            isCaptureEnabled: isCaptureEnabled,
            separator: separator,
            maxItemCount: maxItemCount,
            maxItemSizeBytes: maxItemSizeBytes,
            suppressAdjacentDuplicates: suppressAdjacentDuplicates,
            persistClipboardContents: persistClipboardContents,
            clearHistoryOnQuit: clearHistoryOnQuit,
            ignoredAppNames: ignoredAppNames,
            ignoredAppBundleIdentifiers: ignoredAppBundleIdentifiers,
            ignoredPasteboardTypes: ignoredPasteboardTypes,
            sensitiveContentPatterns: sensitiveContentPatterns
        )
    }

    private static func clampedItemCount(_ value: Int) -> Int {
        min(max(value, 1), 500)
    }

    private static func clampedItemSize(_ value: Int) -> Int {
        min(max(value, 1_024), 10_000_000)
    }
}
extension ClipboardSettings {
    private enum CodingKeys: String, CodingKey {
        case isCaptureEnabled
        case separator
        case maxItemCount
        case maxItemSizeBytes
        case suppressAdjacentDuplicates
        case persistClipboardContents
        case clearHistoryOnQuit
        case ignoredAppNames
        case ignoredAppBundleIdentifiers
        case ignoredPasteboardTypes
        case sensitiveContentPatterns
    }

    init(from decoder: Decoder) throws {
        let defaults = ClipboardSettings()
        let container = try decoder.container(keyedBy: CodingKeys.self)

        self.init(
            isCaptureEnabled: try container.decodeIfPresent(Bool.self, forKey: .isCaptureEnabled) ?? defaults.isCaptureEnabled,
            separator: try container.decodeIfPresent(String.self, forKey: .separator) ?? defaults.separator,
            maxItemCount: try container.decodeIfPresent(Int.self, forKey: .maxItemCount) ?? defaults.maxItemCount,
            maxItemSizeBytes: try container.decodeIfPresent(Int.self, forKey: .maxItemSizeBytes) ?? defaults.maxItemSizeBytes,
            suppressAdjacentDuplicates: try container.decodeIfPresent(Bool.self, forKey: .suppressAdjacentDuplicates) ?? defaults.suppressAdjacentDuplicates,
            persistClipboardContents: try container.decodeIfPresent(Bool.self, forKey: .persistClipboardContents) ?? defaults.persistClipboardContents,
            clearHistoryOnQuit: try container.decodeIfPresent(Bool.self, forKey: .clearHistoryOnQuit) ?? defaults.clearHistoryOnQuit,
            ignoredAppNames: try container.decodeIfPresent([String].self, forKey: .ignoredAppNames) ?? defaults.ignoredAppNames,
            ignoredAppBundleIdentifiers: try container.decodeIfPresent([String].self, forKey: .ignoredAppBundleIdentifiers) ?? defaults.ignoredAppBundleIdentifiers,
            ignoredPasteboardTypes: try container.decodeIfPresent([String].self, forKey: .ignoredPasteboardTypes) ?? defaults.ignoredPasteboardTypes,
            sensitiveContentPatterns: try container.decodeIfPresent([String].self, forKey: .sensitiveContentPatterns) ?? defaults.sensitiveContentPatterns
        )
    }
}
