import Foundation

struct ClipboardSettings: Codable, Equatable {
    var isCaptureEnabled: Bool
    var separator: String
    var maxItemCount: Int
    var maxItemSizeBytes: Int
    var suppressAdjacentDuplicates: Bool
    var ignoredAppNames: [String]
    var ignoredAppBundleIdentifiers: [String]
    var ignoredPasteboardTypes: [String]
    var sensitiveContentPatterns: [String]

    init(
        isCaptureEnabled: Bool = true,
        separator: String = "\n\n",
        maxItemCount: Int = 100,
        maxItemSizeBytes: Int = 1_000_000,
        suppressAdjacentDuplicates: Bool = true,
        ignoredAppNames: [String] = ClipboardSettings.defaultIgnoredAppNames,
        ignoredAppBundleIdentifiers: [String] = ClipboardSettings.defaultIgnoredAppBundleIdentifiers,
        ignoredPasteboardTypes: [String] = ClipboardSettings.defaultIgnoredPasteboardTypes,
        sensitiveContentPatterns: [String] = ClipboardSettings.defaultSensitiveContentPatterns
    ) {
        self.isCaptureEnabled = isCaptureEnabled
        self.separator = separator
        self.maxItemCount = Self.clampedItemCount(maxItemCount)
        self.maxItemSizeBytes = Self.clampedItemSize(maxItemSizeBytes)
        self.suppressAdjacentDuplicates = suppressAdjacentDuplicates
        self.ignoredAppNames = Self.sanitizedList(ignoredAppNames)
        self.ignoredAppBundleIdentifiers = Self.sanitizedList(ignoredAppBundleIdentifiers)
        self.ignoredPasteboardTypes = Self.sanitizedList(ignoredPasteboardTypes)
        self.sensitiveContentPatterns = Self.sanitizedList(sensitiveContentPatterns)
    }

    static let defaultIgnoredPasteboardTypes: [String] = [
        PasteboardTypeNames.transient,
        PasteboardTypeNames.concealed,
        PasteboardTypeNames.autogenerated,
        PasteboardTypeNames.onePassword,
        PasteboardTypeNames.typeIt4Me,
        PasteboardTypeNames.peterMaurerTransient,
        PasteboardTypeNames.pasteboardGenerator,
        PasteboardTypeNames.keeWeb
    ]

    static let defaultIgnoredAppNames: [String] = [
        "1Password",
        "Bitwarden",
        "Dashlane",
        "Enpass",
        "Keeper",
        "KeePass",
        "Keychain Access",
        "LastPass",
        "NordPass",
        "Proton Pass",
        "Secrets",
        "Strongbox"
    ]

    static let defaultIgnoredAppBundleIdentifiers: [String] = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.apple.keychainaccess",
        "com.bitwarden.desktop",
        "com.dashlane.dashlanephonefinal",
        "com.keepersecurity.KeeperPasswordManager",
        "com.lastpass.LastPass",
        "com.proton.pass.mac",
        "com.strongbox.mac"
    ]

    static let defaultSensitiveContentPatterns: [String] = [
        #"\b(password|passwd|passphrase)\s*[:=]"#,
        #"\b(api[_-]?key|secret|token)\s*[:=]"#,
        #"-----BEGIN (RSA |EC |OPENSSH |PGP )?PRIVATE KEY-----"#
    ]

    func normalized() -> ClipboardSettings {
        ClipboardSettings(
            isCaptureEnabled: isCaptureEnabled,
            separator: separator,
            maxItemCount: maxItemCount,
            maxItemSizeBytes: maxItemSizeBytes,
            suppressAdjacentDuplicates: suppressAdjacentDuplicates,
            ignoredAppNames: ignoredAppNames,
            ignoredAppBundleIdentifiers: ignoredAppBundleIdentifiers,
            ignoredPasteboardTypes: ignoredPasteboardTypes,
            sensitiveContentPatterns: sensitiveContentPatterns
        )
    }

    static func sanitizedList(_ values: [String]) -> [String] {
        var seen: Set<String> = []

        return values.compactMap { value in
            let sanitized = value.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !sanitized.isEmpty else {
                return nil
            }

            let key = sanitized.lowercased()
            guard seen.insert(key).inserted else {
                return nil
            }

            return sanitized
        }
    }

    private static func clampedItemCount(_ value: Int) -> Int {
        min(max(value, 1), 500)
    }

    private static func clampedItemSize(_ value: Int) -> Int {
        min(max(value, 1_024), 10_000_000)
    }
}
