import XCTest
@testable import ChainCopy

final class CaptureEngineTests: XCTestCase {
    private let engine = CaptureEngine()

    func testCapturesTextWithSourceMetadataAndHash() {
        let decision = engine.evaluate(
            snapshot: snapshot(
                text: "Alpha",
                sourceApplication: SourceApplication(name: "Safari", bundleIdentifier: "com.apple.Safari")
            ),
            method: .appendModeClipboardChange,
            existingItems: [],
            settings: ClipboardSettings(),
            ownWriteTracker: OwnPasteboardWriteTracker()
        )

        guard case let .captured(item) = decision else {
            return XCTFail("Expected captured item")
        }

        XCTAssertEqual(item.text, "Alpha")
        XCTAssertEqual(item.sourceAppName, "Safari")
        XCTAssertEqual(item.sourceAppBundleIdentifier, "com.apple.Safari")
        XCTAssertEqual(item.captureMethod, .appendModeClipboardChange)
        XCTAssertEqual(item.contentKind, .text)
        XCTAssertEqual(item.contentHash, ContentHasher.hash("Alpha"))
        XCTAssertEqual(item.pasteboardChangeCount, 1)
    }

    func testIgnoresTransientConcealedAndAutogeneratedTypes() {
        for ignoredType in [
            PasteboardTypeNames.transient,
            PasteboardTypeNames.concealed,
            PasteboardTypeNames.autogenerated
        ] {
            let decision = engine.evaluate(
                snapshot: snapshot(text: "Secret", types: [PasteboardTypeNames.string, ignoredType]),
                method: .appendModeClipboardChange,
                existingItems: [],
                settings: ClipboardSettings(),
                ownWriteTracker: OwnPasteboardWriteTracker()
            )

            assertIgnored(decision, .privacy(.ignoredPasteboardType(ignoredType)))
        }
    }

    func testIgnoresConfiguredSourceApplicationName() {
        let decision = engine.evaluate(
            snapshot: snapshot(
                text: "Secret",
                sourceApplication: SourceApplication(name: "1Password", bundleIdentifier: "com.example.password")
            ),
            method: .appendModeClipboardChange,
            existingItems: [],
            settings: ClipboardSettings(),
            ownWriteTracker: OwnPasteboardWriteTracker()
        )

        assertIgnored(decision, .privacy(.ignoredSourceApp))
    }

    func testIgnoresConfiguredSourceBundleIdentifier() {
        let decision = engine.evaluate(
            snapshot: snapshot(
                text: "Secret",
                sourceApplication: SourceApplication(name: "Security Helper", bundleIdentifier: "com.bitwarden.desktop")
            ),
            method: .appendModeClipboardChange,
            existingItems: [],
            settings: ClipboardSettings(),
            ownWriteTracker: OwnPasteboardWriteTracker()
        )

        assertIgnored(decision, .privacy(.ignoredSourceApp))
    }

    func testIgnoresAdjacentDuplicateByContentHash() {
        let existing = ClipItem(text: "Alpha")
        let decision = engine.evaluate(
            snapshot: snapshot(text: "Alpha"),
            method: .appendModeClipboardChange,
            existingItems: [existing],
            settings: ClipboardSettings(),
            ownWriteTracker: OwnPasteboardWriteTracker()
        )

        assertIgnored(decision, .duplicateOfLatestItem)
    }

    func testAllowsDuplicateWhenSuppressionDisabled() {
        let existing = ClipItem(text: "Alpha")
        let decision = engine.evaluate(
            snapshot: snapshot(text: "Alpha"),
            method: .appendModeClipboardChange,
            existingItems: [existing],
            settings: ClipboardSettings(suppressAdjacentDuplicates: false),
            ownWriteTracker: OwnPasteboardWriteTracker()
        )

        guard case .captured = decision else {
            return XCTFail("Expected duplicate to be captured when suppression is disabled")
        }
    }

    func testRejectsOversizedItems() {
        let oversizedText = String(repeating: "a", count: 1_025)
        let decision = engine.evaluate(
            snapshot: snapshot(text: oversizedText),
            method: .appendModeClipboardChange,
            existingItems: [],
            settings: ClipboardSettings(maxItemSizeBytes: 1_024),
            ownWriteTracker: OwnPasteboardWriteTracker()
        )

        assertIgnored(decision, .privacy(.oversizedText(maxBytes: 1_024, actualBytes: 1_025)))
    }

    func testRejectsRichTextPlaceholderWhenNoPlainTextExists() {
        let decision = engine.evaluate(
            snapshot: PasteboardCaptureSnapshot(
                changeCount: 8,
                types: [PasteboardTypeNames.rtf],
                content: .richTextPlaceholder(types: [PasteboardTypeNames.rtf])
            ),
            method: .appendModeClipboardChange,
            existingItems: [],
            settings: ClipboardSettings(),
            ownWriteTracker: OwnPasteboardWriteTracker()
        )

        assertIgnored(decision, .unsupportedContent(.richText))
    }

    func testIgnoresOwnWriteByMarkerType() {
        let decision = engine.evaluate(
            snapshot: snapshot(text: "Joined", types: [PasteboardTypeNames.string, PasteboardTypeNames.chainCopyOwnedWrite]),
            method: .appendModeClipboardChange,
            existingItems: [],
            settings: ClipboardSettings(),
            ownWriteTracker: OwnPasteboardWriteTracker()
        )

        assertIgnored(decision, .ownWrite)
    }

    func testIgnoresOwnWriteByRecordedChangeCount() {
        let tracker = OwnPasteboardWriteTracker()
        tracker.record(changeCount: 42)

        let decision = engine.evaluate(
            snapshot: snapshot(text: "Joined", changeCount: 42),
            method: .appendModeClipboardChange,
            existingItems: [],
            settings: ClipboardSettings(),
            ownWriteTracker: tracker
        )

        assertIgnored(decision, .ownWrite)
    }

    func testIgnoresConfiguredSensitiveContentPatterns() {
        let decision = engine.evaluate(
            snapshot: snapshot(text: "api_key = super-secret"),
            method: .appendModeClipboardChange,
            existingItems: [],
            settings: ClipboardSettings(),
            ownWriteTracker: OwnPasteboardWriteTracker()
        )

        assertIgnored(decision, .privacy(.sensitiveContentPattern))
    }

    private func snapshot(
        text: String,
        changeCount: Int = 1,
        types: Set<String> = [PasteboardTypeNames.string],
        sourceApplication: SourceApplication? = nil
    ) -> PasteboardCaptureSnapshot {
        PasteboardCaptureSnapshot(
            changeCount: changeCount,
            types: types,
            content: .plainText(text, types: types),
            sourceApplication: sourceApplication
        )
    }

    private func assertIgnored(
        _ decision: CaptureDecision,
        _ expectedReason: CaptureRejectionReason,
        file: StaticString = #filePath,
        line: UInt = #line
    ) {
        guard case let .ignored(reason) = decision else {
            return XCTFail("Expected ignored decision", file: file, line: line)
        }

        XCTAssertEqual(reason, expectedReason, file: file, line: line)
    }
}
