import AppKit
import Foundation

enum PasteboardTypeNames {
    static let chainCopyOwnedWrite = "com.abhinavgupta.ChainCopy.owned-write"

    static let transient = "org.nspasteboard.TransientType"
    static let concealed = "org.nspasteboard.ConcealedType"
    static let autogenerated = "org.nspasteboard.AutoGeneratedType"

    static let onePassword = "com.agilebits.onepassword"
    static let typeIt4Me = "com.typeit4me.clipping"
    static let peterMaurerTransient = "de.petermaurer.TransientPasteboardType"
    static let pasteboardGenerator = "Pasteboard generator type"
    static let keeWeb = "net.antelle.keeweb"

    static let string = NSPasteboard.PasteboardType.string.rawValue
    static let url = NSPasteboard.PasteboardType.URL.rawValue
    static let fileURL = NSPasteboard.PasteboardType.fileURL.rawValue
    static let rtf = NSPasteboard.PasteboardType.rtf.rawValue
    static let rtfd = NSPasteboard.PasteboardType.rtfd.rawValue
    static let html = NSPasteboard.PasteboardType.html.rawValue

    static let richTextTypes: Set<String> = [
        rtf,
        rtfd,
        html
    ]
}

extension NSPasteboard.PasteboardType {
    static let chainCopyOwnedWrite = NSPasteboard.PasteboardType(PasteboardTypeNames.chainCopyOwnedWrite)
}
